/**
 * Local mock AI adapter — the default. Deterministic, offline, and routed
 * through the same schema validation as a real provider, so the boundary is
 * exercised in Demo Mode too.
 */
import type { AiRecommendation, RiskVerdict } from '../../types';
import { applyAiOutput } from './guard';
import type { AiAdapter, AiExplainInput } from './types';

const RECOMMENDATION_BY_VERDICT: Record<RiskVerdict, AiRecommendation> = {
  LOW_RISK: 'APPROVE_FOR_REVIEW',
  REVIEW_REQUIRED: 'REQUIRE_REVIEW',
  INSUFFICIENT_DATA: 'REQUIRE_REVIEW',
  BLOCKED: 'BLOCK',
};

function factValue(input: AiExplainInput, id: string): string {
  return input.facts.find((fact) => fact.id === id)?.value ?? 'unknown';
}

export function createMockAiAdapter(): AiAdapter {
  return {
    name: 'Local mock adapter',
    kind: 'mock',
    async explain(input: AiExplainInput) {
      const { assessment } = input;
      const failing = assessment.checks.filter(
        (check) => check.status === 'FAIL' || check.status === 'INSUFFICIENT_DATA',
      );

      const summary =
        failing.length === 0
          ? `Transfer of ${factValue(input, 'fact.value')} to an allowlisted recipient using an allowed method.`
          : `${failing.length} policy check${failing.length === 1 ? '' : 's'} did not pass: ` +
            `${failing.map((check) => check.label.toLowerCase()).join('; ')}.`;

      const rationale = [
        `The policy engine evaluated this event on chain ${factValue(input, 'fact.chainId')} and returned ${assessment.verdict}.`,
        `Recipient ${factValue(input, 'fact.to')} allowlisted: ${factValue(input, 'fact.recipientAllowlisted')}.`,
        `Value ${factValue(input, 'fact.value')} against a limit of ${factValue(input, 'fact.limit')}.`,
        `Method "${factValue(input, 'fact.method')}" allowlisted: ${factValue(input, 'fact.methodAllowlisted')}.`,
        'This explanation is descriptive only and is not financial advice.',
      ].join(' ');

      const raw = {
        summary,
        rationale,
        citedFactIds: [
          'fact.chainId',
          'fact.to',
          'fact.recipientAllowlisted',
          'fact.value',
          'fact.limit',
          'fact.method',
          'fact.methodAllowlisted',
        ],
        recommendation: RECOMMENDATION_BY_VERDICT[assessment.verdict],
        caveats: [
          'Testnet data only — no real funds are involved.',
          'Generated by the local mock adapter, not a hosted model.',
        ],
      };

      return applyAiOutput(assessment, raw, 'Local mock adapter', input.now).ai;
    },
  };
}
