/**
 * The default AI adapter. It runs offline and deterministically, and its
 * output goes through the same schema validation as a real provider, so the
 * boundary is exercised in Demo Mode too.
 */
import type { AiRecommendation, RiskVerdict } from '../../types';
import { applyAiOutput } from './guard';
import type { AiAdapter, AiExplainInput } from './types';

const RECOMMENDATION_BY_VERDICT: Record<RiskVerdict, AiRecommendation> = {
  LOW_RISK: 'APPROVE_FOR_REVIEW',
  REVIEW_REQUIRED: 'REQUIRE_REVIEW',
  INSUFFICIENT_DATA: 'REQUIRE_REVIEW',
  BLOCKED: 'BLOCK',
};

function factValue(input: AiExplainInput, id: string): string {
  return input.facts.find((fact) => fact.id === id)?.value ?? 'unknown';
}

/** Short names for the rules, so a summary reads as a sentence. */
const RULE_NAME: Record<string, string> = {
  DATA_COMPLETENESS: 'transaction data',
  CHAIN_MATCH: 'chain',
  AMOUNT_LIMIT: 'amount limit',
  RECIPIENT_ALLOWLIST: 'recipient allowlist',
  METHOD_ALLOWLIST: 'method allowlist',
};

function listNames(names: readonly string[]): string {
  if (names.length <= 1) return names[0] ?? '';
  return `${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}`;
}

export function createMockAiAdapter(): AiAdapter {
  return {
    name: 'Local mock adapter',
    kind: 'mock',
    async explain(input: AiExplainInput) {
      const { assessment } = input;
      const failing = assessment.checks.filter(
        (check) => check.status === 'FAIL' || check.status === 'INSUFFICIENT_DATA',
      );

      const failedNames = failing.map((check) => RULE_NAME[check.rule] ?? check.rule.toLowerCase());
      const summary =
        failing.length === 0
          ? `Transfer of ${factValue(input, 'fact.value')} to an allowlisted recipient using an allowed method.`
          : `The ${listNames(failedNames)} check${failing.length === 1 ? '' : 's'} did not pass.`;

      const recipientOnList = factValue(input, 'fact.recipientAllowlisted') === 'true';
      const methodOnList = factValue(input, 'fact.methodAllowlisted') === 'true';
      const rationale = [
        `The policy engine evaluated this event on chain ${factValue(input, 'fact.chainId')} and returned ${assessment.verdict}.`,
        `The recipient ${factValue(input, 'fact.to')} is ${recipientOnList ? 'on' : 'not on'} the allowlist.`,
        `The value is ${factValue(input, 'fact.value')} against a limit of ${factValue(input, 'fact.limit')}.`,
        `The method "${factValue(input, 'fact.method')}" is ${methodOnList ? 'allowed' : 'not on the method allowlist'}.`,
        'This describes testnet activity and is not financial advice.',
      ].join(' ');

      const raw = {
        summary,
        rationale,
        citedFactIds: [
          'fact.chainId',
          'fact.to',
          'fact.recipientAllowlisted',
          'fact.value',
          'fact.limit',
          'fact.method',
          'fact.methodAllowlisted',
        ],
        recommendation: RECOMMENDATION_BY_VERDICT[assessment.verdict],
        caveats: [
          'Testnet data only. No real funds are involved.',
          'Generated by the local mock adapter, not a hosted model.',
        ],
      };

      return applyAiOutput(assessment, raw, 'Local mock adapter', input.now).ai;
    },
  };
}
